version: '2.2'
services:
 dbpostgres:
  build: ./
  volumes:
   - /private/var/lib/postgresql:/var/lib/postgresql/data
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: user
   POSTGRES_PASSWORD: db1234
   POSTGRES_DB: mantenimientodb
 micro1:
  build: ./
  ports:
   - "1080:8080"
  volumes:
   - ./payara-micro/deployments:/opt/payara/deployments